services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: joaovitor98/bangalo-app
    container_name: app
    tty: true
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    networks:
      - bangalo
    environment:
      - APPLICATION_KEY=Plk6JcBo3MQ485PEeWAHTbJH342ASDAS+cPd7Ikn
      - APPLICATION_PORT=3000
      - NODE_ENV=development
      - STORAGE_SERVICE=http://storage:4000/v1
      - APPLICATION_DB_INTEGRATION=postgresql://jo_o:LF8e-06xGSReGCxmLwoWHA@jade-boxer-6962.jxf.gcp-southamerica-east1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full
      - APPLICATION_DB_INTEGRATION_DIALECT=postgres
    depends_on:
      - storage
      - redis
  storage:
    build:
      context: ./plugins/storage
      dockerfile: Dockerfile
    image: joaovitor98/storage-app
    container_name: storage
    tty: true
    environment:
      - APPLICATION_STORAGE_PORT=4000
      - APPLICATION_STORAGE_ACCESS=http://localhost:3000
    volumes:
      - ./plugins/storage:/usr/src/storage
    ports:
      - 4000:4000
    networks:
      - bangalo
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
    networks:
      - bangalo
    volumes:
      - /cache/redis:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: joaovitor98/nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - bangalo
    tty: true
    restart: unless-stopped
    depends_on:
      - app

networks:
  bangalo:
    driver: bridge
